import useSWR from "swr";
import fetcher from "@/lib/fetcher";
import type { DashboardResponse } from "@/types/dashboard";

export const useDashboard = () => {
  // 使用 SWR 獲取伺服器列表數據
  // const data = {
  //   servers: [
  //     {
  //       game: "cs2",
  //       network: "多线",
  //       name: "闲聊大厅 1#",
  //       map: "fys_lobby_liyue",
  //       translation: "璃月港",
  //       currentPlayers: 64,
  //       maxPlayers: 64,
  //       host: "ttt.cs2mg.com",
  //       port: 27900,
  //       mapId: "1f5e0a1e-1d9d-47a3-928d-b49596442dd9",
  //       serverId: 73,
  //       modeId: 2098,
  //     },
  //     {
  //       game: "cs2",
  //       network: "多线",
  //       name: "闲聊大厅 2#",
  //       map: "fys_lobby_liyue",
  //       translation: "璃月港",
  //       currentPlayers: 64,
  //       maxPlayers: 64,
  //       host: "ttt.cs2mg.com",
  //       port: 27901,
  //       mapId: "1f5e0a1e-1d9d-47a3-928d-b49596442dd9",
  //       serverId: 77,
  //       modeId: 2098,
  //     },
  //     {
  //       game: "cs2",
  //       network: "多线",
  //       name: "僵尸逃跑 09#",
  //       map: "ze_ratatouille",
  //       translation: "蔬菜大杂烩",
  //       currentPlayers: 64,
  //       maxPlayers: 64,
  //       host: "s9.cs2ze.com",
  //       port: 27095,
  //       mapId: "664d8fe5-8eef-4486-8b31-977c5a661f4c",
  //       currentStage: 3,
  //       totalStage: 3,
  //       extremeStage: false,
  //       serverId: 67,
  //       modeId: 2001,
  //     },
  //     {
  //       game: "cs2",
  //       network: "多线",
  //       name: "僵尸逃跑 04#",
  //       map: "ze_industrial_dejavu",
  //       translation: "工业循环",
  //       currentPlayers: 63,
  //       maxPlayers: 64,
  //       host: "s4.cs2ze.com",
  //       port: 27045,
  //       mapId: "06592691-d13e-4385-bc29-80ffdcb61b51",
  //       currentStage: 3,
  //       totalStage: 4,
  //       extremeStage: false,
  //       serverId: 60,
  //       modeId: 2001,
  //     },
  //     {
  //       game: "cs2",
  //       network: "多线",
  //       name: "僵尸逃跑 08#",
  //       map: "ze_2025_xmas_world",
  //       translation: "2025圣诞世界",
  //       currentPlayers: 62,
  //       maxPlayers: 64,
  //       host: "s8.cs2ze.com",
  //       port: 27085,
  //       mapId: "625e6e59-f42a-44b7-bbd1-337d2e74e021",
  //       currentStage: 1,
  //       totalStage: 1,
  //       extremeStage: false,
  //       serverId: 66,
  //       modeId: 2001,
  //     },
  //     {
  //       game: "cs2",
  //       network: "多线",
  //       name: "僵尸逃跑 10#",
  //       map: "ze_eizures_b2",
  //       translation: "核子工厂",
  //       currentPlayers: 62,
  //       maxPlayers: 64,
  //       host: "s10.cs2ze.com",
  //       port: 27105,
  //       mapId: "72415645-4b8f-44e9-bbf4-dee27791d799",
  //       currentStage: 1,
  //       totalStage: 1,
  //       extremeStage: false,
  //       serverId: 68,
  //       modeId: 2001,
  //     },
  //     {
  //       game: "cs2",
  //       network: "多线",
  //       name: "僵尸逃跑 01#",
  //       map: "ze_mountain_escape_snow",
  //       translation: "爬雪山",
  //       currentPlayers: 56,
  //       maxPlayers: 64,
  //       host: "s1.cs2ze.com",
  //       port: 27015,
  //       mapId: "a35f003e-9760-4391-ac75-ee6b0b1667dd",
  //       currentStage: 1,
  //       totalStage: 1,
  //       extremeStage: false,
  //       serverId: 55,
  //       modeId: 2001,
  //     },
  //     {
  //       game: "cs2",
  //       network: "多线",
  //       name: "魔兽混战 1#",
  //       map: "de_vertigo",
  //       translation: "殒命大厦",
  //       currentPlayers: 36,
  //       maxPlayers: 36,
  //       host: "s1.cs2war3.com",
  //       port: 27215,
  //       mapId: "3a00b056-baeb-44f5-8c6f-bd67eeb4f5bc",
  //       ctScore: 3,
  //       teScore: 11,
  //       serverId: 80,
  //       modeId: 2010,
  //     },
  //     {
  //       game: "cs2",
  //       network: "多线",
  //       name: "匪镇谍影 1#",
  //       map: "ttt_cs2_tides",
  //       translation: "古堡危机",
  //       currentPlayers: 36,
  //       maxPlayers: 40,
  //       host: "ttt.cs2mg.com",
  //       port: 27035,
  //       mapId: "6e091544-a9c8-48b5-bc37-2c97a249cf69",
  //       serverId: 72,
  //       modeId: 2002,
  //     },
  //     {
  //       game: "cs2",
  //       network: "多线",
  //       name: "僵尸逃跑 05#",
  //       map: "ze_maontain_escape",
  //       translation: "曼波爬雪山",
  //       currentPlayers: 32,
  //       maxPlayers: 64,
  //       host: "s5.cs2ze.com",
  //       port: 27055,
  //       mapId: "b683f3e2-e81f-4cb8-9c9d-d6d207d8b720",
  //       currentStage: 1,
  //       totalStage: 1,
  //       extremeStage: false,
  //       serverId: 61,
  //       modeId: 2001,
  //     },
  //     {
  //       game: "cs2",
  //       network: "多线",
  //       name: "娱乐休闲 1#",
  //       map: "mg_kirbys_brawl_v2",
  //       translation: "*对枪* 星之卡比",
  //       currentPlayers: 13,
  //       maxPlayers: 40,
  //       host: "s1.cs2mg.com",
  //       port: 27025,
  //       mapId: "47db476e-01fd-4396-89be-d8fdcb1f1682",
  //       ctScore: 7,
  //       teScore: 10,
  //       serverId: 56,
  //       modeId: 2004,
  //     },
  //     {
  //       game: "csgo",
  //       network: "多线",
  //       name: "滑翔竞速[SF] 1#",
  //       map: "surf_eunoia",
  //       translation: "尤诺亚",
  //       currentPlayers: 4,
  //       maxPlayers: 28,
  //       host: "sr-1.1mgou.com",
  //       port: 27022,
  //       mapId: "009e9f1d-a861-43a6-a5b3-ffef17a2f634",
  //       serverId: 8,
  //       modeId: 1007,
  //     },
  //     {
  //       game: "cs2",
  //       network: "多线",
  //       name: "僵尸逃跑 03#",
  //       map: "ze_diamond_cube_v1_cs2",
  //       translation: "钻石立方",
  //       currentPlayers: 3,
  //       maxPlayers: 64,
  //       host: "s3.cs2ze.com",
  //       port: 27035,
  //       mapId: "71392569-8c19-4f41-8012-e3be0b0ccdbe",
  //       currentStage: 1,
  //       totalStage: 2,
  //       extremeStage: false,
  //       serverId: 59,
  //       modeId: 2001,
  //     },
  //     {
  //       game: "cs2",
  //       network: "多线",
  //       name: "僵尸逃跑 06#",
  //       map: "ze_potc_p",
  //       translation: "加勒比海盗",
  //       currentPlayers: 1,
  //       maxPlayers: 64,
  //       host: "s6.cs2ze.com",
  //       port: 27065,
  //       mapId: "50945da4-8090-4e85-b6c9-88cfbcba974f",
  //       currentStage: 1,
  //       totalStage: 1,
  //       extremeStage: false,
  //       serverId: 62,
  //       modeId: 2001,
  //     },
  //     {
  //       game: "cs2",
  //       network: "多线",
  //       name: "魔兽混战 2#",
  //       map: "de_inferno",
  //       translation: "炼狱小镇",
  //       currentPlayers: 0,
  //       maxPlayers: 36,
  //       host: "s2.cs2war3.com",
  //       port: 27315,
  //       mapId: "b61f97be-a007-46cf-bea0-3d7a221b07c6",
  //       ctScore: 0,
  //       teScore: 0,
  //       serverId: 82,
  //       modeId: 2010,
  //     },
  //     {
  //       game: "cs2",
  //       network: "多线",
  //       name: "僵尸逃跑 02#",
  //       map: "ze_flying_world",
  //       translation: "空中世界",
  //       currentPlayers: 0,
  //       maxPlayers: 64,
  //       host: "s2.cs2ze.com",
  //       port: 27025,
  //       mapId: "cea1a224-c9a5-4234-99e8-a4ab9700853f",
  //       currentStage: 1,
  //       totalStage: 1,
  //       extremeStage: false,
  //       serverId: 58,
  //       modeId: 2001,
  //     },
  //     {
  //       game: "cs2",
  //       network: "多线",
  //       name: "僵尸逃跑 07#",
  //       map: "ze_death_star_escape_p",
  //       translation: "逃离死星",
  //       currentPlayers: 0,
  //       maxPlayers: 64,
  //       host: "s7.cs2ze.com",
  //       port: 27075,
  //       mapId: "f6b6461c-8f4d-457f-975a-905af036a73a",
  //       currentStage: 1,
  //       totalStage: 1,
  //       extremeStage: false,
  //       serverId: 64,
  //       modeId: 2001,
  //     },
  //     {
  //       game: "csgo",
  //       network: "多线",
  //       name: "魔兽混战[War3] #1",
  //       map: "de_inferno_pro-mod",
  //       translation: "炼狱小镇 GO版",
  //       currentPlayers: 0,
  //       maxPlayers: 37,
  //       host: "w3-1.1mgou.com",
  //       port: 27050,
  //       mapId: "5c9cd18f-9e6c-411d-979c-842e229a3c0f",
  //       ctScore: 0,
  //       teScore: 0,
  //       serverId: 43,
  //       modeId: 1010,
  //     },
  //     {
  //       game: "csgo",
  //       network: "多线",
  //       name: "连跳竞赛[BHOP] 1#",
  //       map: "bhop_jumalauta",
  //       translation: "较长",
  //       currentPlayers: 0,
  //       maxPlayers: 28,
  //       host: "bhop-1.1mgou.com",
  //       port: 27075,
  //       mapId: "00e55927-1a30-457b-bf5f-a606a357fe81",
  //       serverId: 25,
  //       modeId: 1008,
  //     },
  //     {
  //       game: "csgo",
  //       network: "多线",
  //       name: "娱乐休闲[MG] 3#",
  //       map: "mg_mikis_multigames2_beta",
  //       translation: "*游戏* mikis2小游戏",
  //       currentPlayers: 0,
  //       maxPlayers: 35,
  //       host: "1.csgomg.com",
  //       port: 27028,
  //       mapId: "e6fa90fe-6cf8-4afe-a915-b559155ff4cd",
  //       ctScore: 0,
  //       teScore: 0,
  //       serverId: 10,
  //       modeId: 1004,
  //     },
  //     {
  //       game: "csgo",
  //       network: "多线",
  //       name: "匪镇谍影[TT] 3#",
  //       map: "ttt_cgmtsminimini_2014_night",
  //       translation: "曼妥思2014",
  //       currentPlayers: 0,
  //       maxPlayers: 40,
  //       host: "ttt-1.1mgou.com",
  //       port: 27060,
  //       mapId: "5224f7af-07be-4ea9-9af4-b52613e3b7ea",
  //       ctScore: 0,
  //       teScore: 0,
  //       serverId: 7,
  //       modeId: 1002,
  //     },
  //     {
  //       game: "csgo",
  //       network: "多线",
  //       name: "僵尸逃跑[ZE] 19#",
  //       map: "ze_randomizer_c1",
  //       translation: "小游戏精装豪华版",
  //       currentPlayers: 0,
  //       maxPlayers: 64,
  //       host: "19.csgoze.com",
  //       port: 27111,
  //       mapId: "3b605037-f1b6-4a04-ad8b-30b9e5126da5",
  //       currentStage: 1,
  //       totalStage: 1,
  //       extremeStage: false,
  //       serverId: 38,
  //       modeId: 1001,
  //     },
  //   ],
  // };
  const { data, error, isLoading } = useSWR<DashboardResponse>(
    "/api/silverwing/system/dashboard",
    (url) => fetcher(url) as Promise<DashboardResponse>,
    {
      revalidateOnFocus: false,
    },
  );

  return {
    servers: data?.servers || [],
    error,
    isLoading,
  };
};
